#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

AIONBD_BENCH_MIN_RECALL_IVF="${AIONBD_BENCH_MIN_RECALL_IVF:-0.90}" \
AIONBD_BENCH_MIN_RECALL_AUTO="${AIONBD_BENCH_MIN_RECALL_AUTO:-0.90}" \
AIONBD_BENCH_MAX_P95_RATIO_IVF="${AIONBD_BENCH_MAX_P95_RATIO_IVF:-1.00}" \
AIONBD_BENCH_MAX_P95_RATIO_AUTO="${AIONBD_BENCH_MAX_P95_RATIO_AUTO:-1.00}" \
AIONBD_BENCH_MAX_MEMORY_RATIO_IVF="${AIONBD_BENCH_MAX_MEMORY_RATIO_IVF:-1.50}" \
AIONBD_BENCH_MAX_MEMORY_RATIO_AUTO="${AIONBD_BENCH_MAX_MEMORY_RATIO_AUTO:-1.50}" \
python3 scripts/run_search_quality_pipeline.py
